/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.raven.cli;

import org.jline.utils.AttributedString;
import org.jline.utils.AttributedStyle;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.shell.jline.PromptProvider;

@SpringBootApplication
public class RavenCliApplication {

    public final static String DEFAULT_SHELL_FORMAT = "raven-im>>";

    public static void main(String[] args) {
        ConfigurableApplicationContext context = SpringApplication.run(RavenCliApplication.class, args);
    }

    @Bean
    public PromptProvider myPromptProvider() {
        return () -> new AttributedString(DEFAULT_SHELL_FORMAT, AttributedStyle.DEFAULT.foreground(AttributedStyle.YELLOW));
    }
}
